package com.sevdotdev.seeminglyapokedex.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFBF0022)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onPrimaryContainer = Color(0xFF410005)
val md_theme_light_secondary = Color(0xFF6E5E00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFE259)
val md_theme_light_onSecondaryContainer = Color(0xFF211B00)
val md_theme_light_tertiary = Color(0xFF325CAB)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD9E2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001A43)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1A)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A1A)
val md_theme_light_surfaceVariant = Color(0xFFF4DDDB)
val md_theme_light_onSurfaceVariant = Color(0xFF534342)
val md_theme_light_outline = Color(0xFF857372)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_light_inverseSurface = Color(0xFF362F2E)
val md_theme_light_inversePrimary = Color(0xFFFFB3AF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFBF0022)
val md_theme_light_outlineVariant = Color(0xFFD8C1C0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB3AF)
val md_theme_dark_onPrimary = Color(0xFF68000E)
val md_theme_dark_primaryContainer = Color(0xFF930018)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD7)
val md_theme_dark_secondary = Color(0xFFE2C635)
val md_theme_dark_onSecondary = Color(0xFF393000)
val md_theme_dark_secondaryContainer = Color(0xFF534600)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE259)
val md_theme_dark_tertiary = Color(0xFFAFC6FF)
val md_theme_dark_onTertiary = Color(0xFF002D6C)
val md_theme_dark_tertiaryContainer = Color(0xFF104491)
val md_theme_dark_onTertiaryContainer = Color(0xFFD9E2FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A1A)
val md_theme_dark_onBackground = Color(0xFFEDE0DE)
val md_theme_dark_surface = Color(0xFF201A1A)
val md_theme_dark_onSurface = Color(0xFFEDE0DE)
val md_theme_dark_surfaceVariant = Color(0xFF534342)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C1C0)
val md_theme_dark_outline = Color(0xFFA08C8B)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
val md_theme_dark_inversePrimary = Color(0xFFBF0022)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB3AF)
val md_theme_dark_outlineVariant = Color(0xFF534342)
val md_theme_dark_scrim = Color(0xFF000000)


object PokemonColors {
    val water = Color(0xFF006098)
    val fire = Color(0xFFEF7200)
    val grass = Color(0xFF00D863)
    val electric = Color(0xFFF6DE00)
    val dragon = Color(0xFF002F71)
    val ice = Color(0xFF6AFBEF)
    val fairy = Color(0xFFFFE0E9)
    val psychic = Color(0xFFFF6ECA)
    val ghost = Color(0xFF7353C4)
    val dark = Color(0xFF110068)
    val steel = Color(0xFFA8C0FF)
    val flying = Color(0xFF9FAFFF)
    val normal = Color(0xFFFFD4BE)
    val ground = Color(0xFF6D4100)
    val rock = Color(0xFFC1AE93)
    val fighting = Color(0xFF700024)
    val bug = Color(0xFFB9C800)
    val poison = Color(0xFF9E08C1)
    val unknown = Color(0xFF004F56)
}
